import React from "react"
import styled from "styled-components"
import Header from "../Header"
import Footer from "../Footer"

const Wrapper = styled.div`
  padding: 0 30%;
`;
const PolicyText = styled.div`
  font-size: 1.2rem;
  line-height: 1.5;
`;

const Title = styled.div`
  text-align: center;
  font-size: 3rem;
  font-weight: bold;
`;

function Index() {
  return (
    <div>
      <Header />
      <Wrapper>
        <Title>Terms of service</Title>
        <br />
        <PolicyText>
          <h5>General Terms</h5> 
          <br/>
          By accessing and placing an order with Streetswear, you
          confirm that you are in agreement with and bound by the terms of
          service contained in the Terms & Conditions outlined below. These
          terms apply to the entire website and any email or other type of
          communication between you and Streetswear. Under no circumstances
          shall Streetswear team be liable for any direct, indirect, special,
          incidental or consequential damages, including, but not limited to,
          loss of data or profit, arising out of the use, or the inability to
          use, the materials on this site, even if Streetswear team or an
          authorized representative has been advised of the possibility of such
          damages. If your use of materials from this site results in the need
          for servicing, repair or correction of equipment or data, you assume
          any costs thereof. Streetswear will not be responsible for any outcome
          that may occur during the course of usage of our resources. We reserve
          the rights to change prices and revise the resources usage policy in
          any moment. 
          <br/>
          <br/>
          <h5>License</h5>
          <br/> 
          Streetswear grants you a revocable,
          non-exclusive, non-transferable, limited license to download, install
          and use the website strictly in accordance with the terms of this
          Agreement. These Terms & Conditions are a contract between you and
          Streetswear (referred to in these Terms & Conditions as &quot; Streetswear
          &quot; , &quot; us &quot;, &quot; we &quot; or &quot; our &quot;), the provider of the Streetswear website and
          the services accessible from the Streetswear website (which are
          collectively referred to in these Terms & Conditions as the
          &quot; Streetswear Service ). You are agreeing to be bound by these Terms &
          Conditions. If you do not agree to these Terms & Conditions, please do
          not use the Streetswear Service. In these Terms & Conditions, &quot; you &quot;
          refers both to you as an individual and to the entity you represent.
          If you violate any of these Terms & Conditions, we reserve the right
          to cancel your account or block access to your account without notice.
            <br/>
            <br/>
          <h5>Definitions and key terms</h5>
            <br/>
            To help explain things as clearly as
          possible in this Terms & Conditions, every time any of these terms are
          referenced, are strictly defined as: Cookie: small amount of data
          generated by a website and saved by your web browser. It is used to
          identify your browser, provide analytics, remember information about
          you such as your language preference or login information. Company:
          when this terms mention “Company,” “we,” “us,” or “our,” it refers to
          Streetswear, that is responsible for your information under this Terms
          & Conditions. Country: where Streetswear or the owners/founders of
          Streetswear are based, in this case is India Device: any internet
          connected device such as a phone, tablet, computer or any other device
          that can be used to visit Streetswear and use the services. Service:
          refers to the service provided by Streetswear as described in the
          relative terms (if available) and on this platform. Third-party
          service: refers to advertisers, contest sponsors, promotional and
          marketing partners, and others who provide our content or whose
          products or services we think may interest you. Website: Streetswear’s
          site, which can be accessed via this URL: www.Streetswear.in You: a
          person or entity that is registered with Streetswear to use the
          Services.


                  </PolicyText>
        <br />
        <br />
        <br />
        <br />
      </Wrapper>

      <Footer />
    </div>
  );
}

export default Index;
